### ISSUE TITLE
Improvements tracking issue

### ISSUE THREAD

**Issue by sqyyy-jar** [sqyyy-jar/cluster-lang#3]
- [x] change dot access parsing to maybe dot access parsing for more code reuse
- [x] add `public` field everywhere needed
- [x] add `else` and `elseif`
- [ ] add alternate assignment operators
- [ ] add struct instantiation
- [ ] add enum instantiation
- [ ] ~add self parameters~
- [x] add Self type
- [x] add reference types
